services:
  nginx-reverse-proxy:
    container_name: nginx-reverse-proxy
    build: .
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./ssl:/etc/nginx/ssl
    extra_hosts:
      - "host.docker.internal:host-gateway"
