services:
  nginx-reverse-proxy:
    container_name: nginx-reverse-proxy
    build: .
    ports:
      - "8080:443"
    volumes:
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./ssl:/etc/nginx/ssl
